const extracurriculars = [
  "CONSULTING",
  "INVESTMENT BANKING",
"Adopt-A-Physicist",
"Architecture Club",
"Astronomy Club",
"Biology Club",
"Chemistry Club",
"Economics Club",
"Electronics Club",
"Engineering Club",
"English Club",
"Distributive Education Clubs of America",
"History Club",
"Life Sciences Club",
"Literature Club",
"Literary Magazine Club",
"Math Club",
"Mu Alpha Theta: Math Honor Society",
"National Honor Society",
"Peer Tutoring",
"Poetry Club",
"Physics Club",
"Psychology Club",
"Quill and Scroll",
"Robotics Club",
"Science National Honors Society",
"Trivia and Quiz Clubs",
"Web design/coding club",
"Writing Club",
"Academic Competitive Teams",
"Academic Decathlon",
"Academic Triathlon",
"American Mathematics Competitions",
"American Regions Math League",
"Caribou Mathematics Competition",
"Chemistry Olympiad",
"Clean Tech Competition",
"Creative Communication Poetry Contest",
"EconChallenge",
"Educators Rising",
"FIRST Robotics Competition",
"High School Innovation Challenge",
"Intel International Science and Engineering Fair",
"Kids Philosophy Slam",
"Math League",
"National Academic Quiz Tournament",
"National French Contest",
"National History Bee",
"National Spelling Bee",
"Odyssey of the Mind",
"Poetry Out Loud",
"Questions Unlimited",
"Quiz Bowl",
"Science Bowl",
"Science Olympiad",
"Other Trivia and Quiz Competition Teams",
"Animation",
"Anime/Manga Club",
"Art Club",
"Art: drawing, painting",
"Blacksmithing",
"Cartooning",
"Ceramics",
"Drama Club",
"Fashion design",
"Graphic Design",
"Jewelry Making",
"Photography",
"Sculpture",
"Sewing",
"High School Theater Program",
"Community Theater Program",
"Video Game Development Club",
"Weaving",
"Woodworking",
"Other Culture and Language Club",
"African American Student Alliances/Clubs",
"American Sign Language Club",
"Chinese Club",
"French Club",
"German Club",
"International Food Club",
"Latin Club",
"Pacific Islanders Club",
"Russian Club",
"South Asian Student Society",
"Spanish Club",
"African Club",
"Community group",
"4-H",
"Community Festivals",
"Do Something",
"Habitat for Humanity",
"JUNTOS",
"Key Club",
"kids Helping Kids",
"Leo Club",
"Mountaineers Club",
"Sisters on the Runway",
"Local government",
"Community Youth Board",
"Student Council",
"Student Government",
"Community Government",
"Leadership group",
"National Beta Club",
"Peer Leadership Group",
"Media",
"School or local magazine/journal",
"School or local newspaper",
"School or local radio station",
"School or local television channel",
"School or local web site",
"Work on a movie",
"Yearbook Committee",
"Civil Air Patrol",
"Junior ROTC",
"Music",
"Any musical interest club",
"School Chorus/Choir",
"Community Chorus/Choir",
"Church Chorus/Choir",
"Chamber Music Group",
"Concert Band",
"Ensembles",
"Singing Lessons",
"Marching Band",
"Jazz Band",
"Orchestra",
"Solo music",
"Your own band",
"Tri-M Music Honor Society",
"Performance Art",
"Comedy Club",
"Choreography",
"Classic Film Club",
"Dance",
"Film Production Club",
"International Thespian Society",
"Miming",
"Puppetry",
"Slam Poetry Club",
"High School Theater Group",
"Community Theater Group",
"Religious groups / Chaplain's office",
"Roleplaying/Fantasy",
"The Civil War Reenactors",
"Dungeons and Dragons Club",
"Gamers Club",
"LARPing (Live Action Role Playing)",
"Renaissance Faires",
"Social Activism",
"Amnesty International",
"Animal Rights Club",
"Breast Cancer Awareness",
"Cancer Foundation",
"Environmental Club",
"Fair Trade Club",
"Gay-Straight Alliance",
"Girls Lean International",
"NOW—National Organization for Women",
"SADD—Students Against Destructive Decisions",
"Boy Scouts",
"Chess Club",
"Equestrian Club",
"Entrepreneurship Club",
"Future Business Leaders of America (FBLA)",
"Girl Scouts",
"Horticulture Club",
"Model Railroads",
"Quilt Making",
"Political Union",
"Debate Club",
"Euro Challenge",
"Foreign Affairs Club",
"Forensics Team",
"High School Democrats of America",
"High School Fed Challenge",
"Junior Statesmen of America",
"Mock Trial Club",
"Model Congress Club",
"Model United Nations",
"National Speech and Debate Association",
"Speech Club",
"Teenage Republicans",
"Young Democrats of America",
"Sports",
"Baseball and softball",
"Basketball",
"Bodybuilding",
"Cheerleading",
"Climbing Club",
"Cycling",
"Dance Team",
"Fencing",
"Football",
"Golf",
"Gymnastics",
"Hiking Club",
"Hockey",
"Intramural Sports",
"Lacrosse",
"Martial Arts",
"Ping Pong Club",
"Quidditch Clubs",
"Skate Board Club",
"Skiing",
"Soccer",
"Swimming",
"Tennis",
"Track & Field",
"Ultimate Frisbee Club",
"Volleyball",
"Water Polo",
"Yoga Club",
"Technology",
"Blogging",
"Personal Web Site",
"Social Media",
"YouTube Channel",
"Volunteering",
"Adopt-a-Highway",
"Animal rescue",
"Best Buddies International",
"Church outreach",
"Hospital volunteer",
"International volunteer program",
"Mentoring",
"Red Cross Club",
"UNICEF",
"Volunteer Fire Department",
"Work with a local charity",
"Work with a local soup kitchen"];

export default extracurriculars;